version: '3.1'

services:

  battmanage-db:
    image: mongo
    container_name: battmanage-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /apps/battmanage/db:/data/db

    # Facultatif  
    logging:
      driver: loki
      options:
        loki-url: "http://grafana.papamica.fr:3100/loki/api/v1/push"
        loki-external-labels: service={{.Name}}
    networks:
      - proxy

  battmanage-demo:
    image: papamica/battmanage
    container_name: battmanage
    restart: always
    volumes:
      - /apps/battmanage/data/qrcode:/usr/src/app/client/public/assets/qrcode
      - /apps/battmanage/data/batteries:/usr/src/app/client/website/batteries
    depends_on:
      - battmanage-db
    environment:
      DB_HOST: battmanage-db
      DB_PORT: 27017
      DB_USER: root
      DB_PASS: example
      DB_NAME: battmanage
      URL: URL

    # Facultatif  
    logging:
      driver: loki
      options:
        loki-url: "LOKI_URL"
        loki-external-labels: service={{.Name}}
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.battmanage.entrypoints=http"
      - "traefik.http.routers.battmanage.rule=Host(`URL`)"
      - "traefik.http.middlewares.battmanage-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.battmanage.middlewares=battmanage-https-redirect"
      - "traefik.http.routers.battmanage-secure.entrypoints=https"
      - "traefik.http.routers.battmanage-secure.rule=Host(`URL`)"
      - "traefik.http.routers.battmanage-secure.tls=true"
      - "traefik.http.routers.battmanage-secure.tls.certresolver=http"
      - "traefik.http.services.battmanage-secure.loadbalancer.server.port=4000"
      - "traefik.docker.network=proxy"
      - "dockupdater.disable=true"
networks:
  proxy:
    external:
      name: proxy
