version: '3.1'

services:

  batt-mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /apps/battmanage/db:/data/db

  battmanage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: battmanage
    restart: always
    volumes:
      - /apps/battmanage/batteries:/usr/src/app/website/batteries
    ports:
      - 4001:4000
    environment:
      DB_USER: root
      DB_PASSWORD: example
      DB: batt-mongo