version: '3.1'

services:
  batt-mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}
      MONGO_INITDB_DATABASE: ${DB_NAME:-battmanage}
    volumes:
      # - /apps/battmanage/db:/data/db
      - ./database/data:/data/db
    ports:
      - ${DB_PORT:-27017}:${DB_PORT:-27017}
    networks:
      - battmanage-network
  
  mongo-express:
    image: mongo-express
    depends_on:
      - batt-mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}
      ME_CONFIG_MONGODB_SERVER: batt-mongo
    networks:
      - battmanage-network

  battmanage:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: battmanage
    depends_on:
      - batt-mongo
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    #   - /apps/battmanage/batteries:/usr/src/app/client/website/batteries
    #   - /apps/battmanage/qrcode:/usr/src/app/client/public/assets/qrcode
    ports:
      - ${API_MAPPING_PORT:-4001}:${API_PORT:-4000}
    environment:
      DB_HOST: batt-mongo
      DB_PORT: ${DB_PORT:-27017}
      DB_USER: ${MONGO_INITDB_ROOT_USERNAME:-root}
      DB_PASS: ${MONGO_INITDB_ROOT_PASSWORD:-example}
      DB_NAME: ${DB_NAME:-battmanage}
      URL: https://battmanage-demo.papamica.com
    networks:
      - battmanage-network

networks:
  battmanage-network:
    driver: bridge